name: build
on: [push]
jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64 Linux
          path: target/x86_64-unknown-linux-gnu/release/tjm
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64 Windows
          path: target/x86_64-pc-windows-gnu/release/tjm.exe
      - uses: actions/upload-artifact@v2
        with:
          name: ARMv7 Linux
          path: target/armv7-unknown-linux-gnueabihf/release/tjm
  build-mac:
    name: Build Mac
    needs: test
    runs-on: macos-latest
#    env:
#      RUSTFLAGS: "-Clinker=clang-8 -Clinker-plugin-lto -Clink-arg=-fuse-ld=lld"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-apple-darwin
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64 Mac
          path: target/x86_64-apple-darwin/release/tjm