name: build
on: [push]
jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
  build-windows:
    name: Build Windows
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64 Windows
          path: target/x86_64-pc-windows-gnu/release/tjm.exe
  build-linux:
    name: Build Linux
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64 Linux
          path: target/x86_64-unknown-linux-gnu/release/tjm
  build-mac:
    name: Build Mac
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-apple-darwin
      - uses: actions/upload-artifact@v2
        with:
          name: x86_64 Mac
          path: target/x86_64-apple-darwin/release/tjm
  create-release:
    name: Create Release
    needs: [build-windows, build-linux, build-mac]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: bump tag version
        id: bump_tag_version
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump_tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.bump_tag_version.outputs.new_tag }}
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v2
        id: download-compiled-artifacts
        with:
          path: artifacts
      - uses: papeloto/action-zip@v1
        with:
          files: 'artifacts/'
          recursive: false
          dest: binaries.zip
      - name: Upload Assets
        id: upload-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./binaries.zip
          asset_name: binaries.zip
          asset_content_type: application/zip
